# Generated by Django 6.0.5 on 2026-05-24 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartao_categoria_graficofinanceiro_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metafinanceira',
            old_name='data_limite',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='metafinanceira',
            old_name='valor_meta',
            new_name='valor_objetivo',
        ),
        migrations.RenameField(
            model_name='saldo',
            old_name='valor_total',
            new_name='valor_atual',
        ),
        migrations.RemoveField(
            model_name='historicofinanceiro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='limitegastos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='metafinanceira',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pagamentorecorrente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='grafico',
        ),
        migrations.RemoveField(
            model_name='relatoriofinanceiro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='nome',
            field=models.CharField(default='Meta Padrão', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafinanceira',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gastocartao',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicofinanceiro',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagamentorecorrente',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relatoriofinanceiro',
            name='data_geracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='relatoriofinanceiro',
            name='formato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='data_ultima_atualizacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('ultimo_acesso', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
