# Generated by Django 6.0.5 on 2026-05-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_data_limite_metafinanceira_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='graficofinanceiro',
            name='dados',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
