# Generated by Django 6.0.5 on 2026-05-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cartao_usuario_alter_graficofinanceiro_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitegastos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
    ]
